import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{BookOpen,Brain,ChevronRight,Clock3,FileText,History,Home,ListChecks,Plus,Search,Sparkles,Target,Trash2,Upload,X}from"lucide-react";
import"./styles.css";
const demo={id:"demo",title:"Mitose — cours de démonstration",pages:[
{id:"p1",n:1,text:"Le centrosome est le principal centre organisateur des microtubules. Il est constitué de deux centrioles disposés perpendiculairement, entourés de matériel péricentriolaire."},
{id:"p2",n:2,text:"Aurora B participe au dispositif de contrôle des accrochages des kinétochores. La mise sous tension du centromère réduit l'activité de ce dispositif de contrôle."},
{id:"p3",n:3,text:"Les microtubules du fuseau sont constitués de tubuline. Leur extrémité + présente une dynamique importante au cours de la mitose."}]};
const levels=[["again","🔴","Pas du tout",10],["hard","🟠","Difficile",1440],["medium","🟡","Moyen",4320],["good","🟢","Bien acquis",10080],["perfect","🔵","Parfait",30240]];
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
function App(){
const[courses,setCourses]=useState(()=>load("rmed_courses",[demo])),[cards,setCards]=useState(()=>load("rmed_cards",[])),[history,setHistory]=useState(()=>load("rmed_history",[]));
const[tab,setTab]=useState("home"),[course,setCourse]=useState(demo),[p,setP]=useState(demo.pages[0]),[sel,setSel]=useState(""),[edit,setEdit]=useState(false),[front,setFront]=useState(""),[back,setBack]=useState(""),[search,setSearch]=useState(""),[revealed,setRevealed]=useState(false),[ri,setRi]=useState(0),[qcm,setQcm]=useState(null);
useEffect(()=>localStorage.setItem("rmed_courses",JSON.stringify(courses)),[courses]);useEffect(()=>localStorage.setItem("rmed_cards",JSON.stringify(cards)),[cards]);useEffect(()=>localStorage.setItem("rmed_history",JSON.stringify(history)),[history]);
const due=useMemo(()=>cards.filter(c=>!c.next||c.next<=Date.now()),[cards,history]);const rc=due[ri];
const nav=t=>{setTab(t);if(t==="review"){setRi(0);setRevealed(false)}};
function open(c,pg=c.pages[0]){setCourse(c);setP(pg);setTab("course")}
function importPdf(e){const f=e.target.files?.[0];if(!f)return;const c={id:crypto.randomUUID(),title:f.name.replace(/\.pdf$/i,""),pages:[{id:crypto.randomUUID(),n:1,text:"PDF importé : "+f.name+" — le lecteur PDF complet sera connecté dans la prochaine version."}]};setCourses(x=>[...x,c]);open(c)}
function makeCard(){const s=sel.trim();setFront(s?"Que faut-il retenir sur « "+s.slice(0,100)+" » ?":"");setBack(s);setEdit(true)}
function save(){if(!front.trim()||!back.trim())return;setCards(x=>[...x,{id:crypto.randomUUID(),courseId:course.id,pageId:p.id,page:p.n,source:sel||back,front:front.trim(),back:back.trim(),level:null,next:Date.now(),created:Date.now()}]);setEdit(false);setSel("")}
function rate(l){if(!rc)return;const days=levels.find(x=>x[0]===l)[3];setCards(x=>x.map(c=>c.id===rc.id?{...c,level:l,next:Date.now()+days*60000,last:Date.now()}:c));setHistory(x=>[{id:crypto.randomUUID(),card:rc.front,level:l,date:Date.now()},...x]);setRevealed(false);setRi(i=>i+1)}
return <div className="app"><aside><div className="logo">R</div><h2>RMed</h2><small>PASS • révision active</small><Nav icon={<Home/>} t="Accueil" a={tab==="home"} f={()=>nav("home")}/><Nav icon={<BookOpen/>} t="Cours" a={tab==="course"} f={()=>nav("course")}/><Nav icon={<Brain/>} t="Flashcards" a={tab==="cards"} f={()=>nav("cards")}/><Nav icon={<Target/>} t="Réviser" a={tab==="review"} f={()=>nav("review")}/><Nav icon={<ListChecks/>} t="QCM" a={tab==="qcm"} f={()=>nav("qcm")}/><Nav icon={<History/>} t="Historique" a={tab==="history"} f={()=>nav("history")}/><div className="dog">🐶<span>Ton compagnon est prêt.</span></div></aside>
<main><header><b className="mobile">RMed</b><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher…"/></div><div className="avatar">R</div></header>
{tab==="home"&&<Home cards={cards} due={due.length} courses={courses} nav={nav} open={open}/>}
{tab==="course"&&<Course course={course} p={p} setP={setP} sel={sel} setSel={setSel} make={makeCard} importPdf={importPdf} courses={courses} open={open}/>}
{tab==="cards"&&<Cards cards={cards} search={search} open={(c)=>{const co=courses.find(x=>x.id===c.courseId);const pg=co?.pages.find(x=>x.id===c.pageId)||co?.pages[0];if(co)open(co,pg)}} del={id=>setCards(x=>x.filter(c=>c.id!==id))}/>}
{tab==="review"&&<Review rc={rc} revealed={revealed} setRevealed={setRevealed} rate={rate} total={due.length} i={ri}/>}
{tab==="qcm"&&<QCM cards={cards} qcm={qcm} setQcm={setQcm}/>}
{tab==="history"&&<HistoryPage h={history}/>}</main>
{edit&&<div className="overlay"><div className="modal"><div className="mh"><h2>Créer ma flashcard</h2><button onClick={()=>setEdit(false)}><X/></button></div><label>Question<input value={front} onChange={e=>setFront(e.target.value)}/></label><label>Réponse<textarea rows="4" value={back} onChange={e=>setBack(e.target.value)}/></label><div className="source"><b>Source exacte</b><p>« {sel||back} »</p><small>{course.title} • page {p.n}</small></div><div className="ai"><Sparkles size={18}/><span>L’IA pourra ensuite proposer une meilleure formulation sans remplacer ton choix.</span></div><div className="actions"><button onClick={()=>setEdit(false)}>Annuler</button><button className="primary" onClick={save}>Créer la carte</button></div></div></div>}</div>
}
function Nav({icon,t,a,f}){return <button className={a?"nav active":"nav"} onClick={f}>{icon}<span>{t}</span></button>}
function Home({cards,due,courses,nav,open}){return <div className="page"><section className="hero"><div><small>TON ESPACE DE RÉVISION</small><h1>Travaille ton cours au moment où tu le lis.</h1><p>Surligne → crée ta flashcard → relie-la au passage exact → révise.</p><button className="primary" onClick={()=>nav("course")}>Ouvrir un cours <ChevronRight/></button></div><div className="bigdog">🐶</div></section><div className="stats"><Stat n={courses.length} t="Cours"/><Stat n={cards.length} t="Flashcards"/><Stat n={due} t="À réviser"/><Stat n={cards.filter(c=>c.level==="perfect"||c.level==="good").length} t="Bien acquis"/></div><div className="grid"><section className="panel"><h3>Continuer</h3>{courses.map(c=><button className="course" key={c.id} onClick={()=>open(c)}><FileText/><div><b>{c.title}</b><small>{c.pages.length} page(s)</small></div><ChevronRight/></button>)}</section><section className="panel"><h3>Actions rapides</h3><div className="quick"><button onClick={()=>nav("review")}><Brain/>Réviser</button><button onClick={()=>nav("qcm")}><ListChecks/>Faire un QCM</button><button onClick={()=>nav("cards")}><Target/>Mes flashcards</button></div></section></div></div>}
function Stat({n,t}){return <div className="stat"><strong>{n}</strong><span>{t}</span></div>}
function Course({course,p,setP,sel,setSel,make,importPdf,courses,open}){return <div className="page"><div className="title"><h1>Cours</h1><label className="upload"><Upload/>Importer un PDF<input type="file" accept=".pdf" onChange={importPdf}/></label></div><div className="reader"><aside className="courseSide">{courses.map(c=><button className={c.id===course.id?"selected":""} key={c.id} onClick={()=>open(c)}><FileText/>{c.title}</button>)}</aside><section><div className="tabs">{course.pages.map(pg=><button className={pg.id===p.id?"selected":""} key={pg.id} onClick={()=>setP(pg)}>Page {pg.n}</button>)}</div><article className="paper"><small>{course.title} • PAGE {p.n}</small><p onMouseUp={()=>{const s=window.getSelection()?.toString();if(s)setSel(s)}}>{p.text}</p><p className="hint">Sélectionne une information dans le texte. Ta sélection devient la source exacte de ta flashcard.</p>{sel&&<div className="selection"><span>« {sel} »</span><button className="primary" onClick={make}><Plus/>Créer une flashcard</button></div>}</article></section></div></div>}
function Cards({cards,search,open,del}){const arr=cards.filter(c=>(c.front+" "+c.back).toLowerCase().includes(search.toLowerCase()));return <div className="page"><div className="title"><h1>Flashcards</h1><span>{cards.length} cartes</span></div>{arr.length?<div className="list">{arr.map(c=><div className="cardrow" key={c.id}><span className="emoji">{levels.find(x=>x[0]===c.level)?.[1]||"⚪"}</span><div><b>{c.front}</b><p>{c.back}</p><small>Page {c.page} • liée au cours</small></div><button onClick={()=>open(c)}>Voir source</button><button className="danger" onClick={()=>del(c.id)}><Trash2/></button></div>)}</div>:<Empty text="Aucune flashcard pour l’instant."/>}</div>}
function Review({rc,revealed,setRevealed,rate,total,i}){if(!rc)return <div className="page empty"><Brain/><h2>Tout est à jour 🎉</h2><p>Aucune flashcard à réviser pour le moment.</p></div>;return <div className="page review"><div className="title"><div><small>RÉVISION ACTIVE</small><h1>Carte {Math.min(i+1,total)}/{total}</h1></div><span className="pill">5 niveaux de maîtrise</span></div><section className="reviewcard"><small>QUESTION</small><h2>{rc.front}</h2>{revealed?<><div className="answer">{rc.back}</div><p>Comment tu maîtrises cette carte ?</p><div className="levels">{levels.map(x=><button key={x[0]} onClick={()=>rate(x[0])}><span>{x[1]}</span><b>{x[2]}</b></button>)}</div></>:<button className="primary reveal" onClick={()=>setRevealed(true)}>Afficher la réponse</button>}</section></div>}
function QCM({cards,qcm,setQcm}){if(!qcm)return <div className="page empty"><ListChecks/><h2>QCM basé sur tes cartes</h2><p>Une question simple est générée à partir de ton contenu.</p><button className="primary" onClick={()=>setQcm(cards[0]?{q:cards[0].front,a:cards[0].back}:null)}>Commencer</button>{!cards.length&&<small>Crée d’abord une flashcard.</small>}</div>;return <div className="page"><div className="title"><h1>QCM</h1><button onClick={()=>setQcm(null)}>Quitter</button></div><section className="panel qcm"><small>QUESTION</small><h2>{qcm.q}</h2><button onClick={()=>alert("Réponse : "+qcm.a)}>Afficher la correction</button></section></div>}
function HistoryPage({h}){return <div className="page"><div className="title"><h1>Historique</h1><span>{h.length} révisions</span></div>{h.length?<div className="list">{h.map(x=><div className="history" key={x.id}><span>{levels.find(l=>l[0]===x.level)?.[1]}</span><div><b>{x.card}</b><small>{new Date(x.date).toLocaleString("fr-FR")}</small></div></div>)}</div>:<Empty text="Ton historique apparaîtra ici."/>}</div>}
function Empty({text}){return <div className="empty"><Clock3/><p>{text}</p></div>}
createRoot(document.getElementById("root")).render(<App/>);